### ISSUE TITLE
Prašome pasirinkti norimą paštomatą

### ISSUE THREAD

**Issue by meshkowich** [zefy/lp-express-shipping-method-for-woocommerce#1]
Druing checkout the plugin shows error requesting user to choose a delivery terminal despite another shipping option being checked.

**Comment by vvoi** [comment]
hi,  i'm not a coder, but i managed to fix this by editing **includes/class-wc-lpexpress-terminals-shipping-method.php** file.

i have changed function **validate_user_selected_terminal** like this:

`

	/**
	 * Validates user submitted terminal
	 *
	 * @param  array $posted Checkout data
	 *
	 * @return void
	 */
	public function validate_user_selected_terminal( $posted ) {
		// Preferred error text
		$error = __( 'Please select a parcel terminal', 'lp-express-shipping-method-for-woocommerce' );

        global $woocommerce;
        $chosen_methods = WC()->session->get( 'chosen_shipping_methods' );
        $chosen_shipping = $chosen_methods[0];

        if ( $chosen_shipping == 'lpexpress_terminals' ) {
    
            // Be sure shipping method was posted
            if( ! isset( $posted['shipping_method'] ) || ! is_array( $posted['shipping_method'] ) ) {
                wc_add_notice( $error, 'error' );
                return;
            }

            // Check if it's correct shipping method
            if( ! in_array( $this->id, $posted['shipping_method'] ) ) {
                wc_add_notice( $error, 'error' );
                return;
            }

            // Check if our field was submitted
            if( ! isset( $_POST[ $this->field_name ] ) || '' == $_POST[ $this->field_name ] || NULL == $_POST[ $this->field_name ] ) {
                wc_add_notice( $error, 'error' );
                return;
            }

            // Finally check if this terminal id exists
            if( NULL == $this->get_terminal_info( $_POST[ $this->field_name ] ) ) {
                wc_add_notice( $error, 'error' );
                return;
            }
            
        }
        
	}

`

i know, editing plugin files is bad idea, but it fixed the problem.

looking forward for updated version of plugin.

**Comment by zefy** [comment]
@meshkowich Thank you for reporting this issue. 
@vvoi Thank you for your solution and contribution to this plugin. I did it a little bit different.

This bug is fixed.

**Comment by Kovas** [comment]
Actually, I'm still getting this error. Doesn't matter which method is chosen, you still have to pick a terminal.

**Comment by zefy** [comment]
Make sure that you're using latest version. Also you could try reinstall plugin and/or clear cache.

**Comment by Kovas** [comment]
Well, plugin was installed today, but I've deleted shipping zone, added it again and it solved my problem. I guess there was a conflict with some other plugin I've tried before.

Btw, any chance you could expand this plugin and add more shipping options, like [Venipak](https://go.venipak.lt/ws/get_pickup_points)?
